### ISSUE TITLE
Не видит игру 

### ISSUE THREAD

**Issue by s1lentman** [xvitaly/srcrepair#575]
### Question

Изначально работал отлично, никаких махинаций с приложением не производил, потом через время Source Repair перестал видеть Team Fortress 2, хотя отлично видел Insurgency и Garry's mod, попробовал разные версии софта и ничего не изменялось, по итогу удалил две видимые игры и теперь просто ошибка что приложение не видит ничего и требует загрузки определённых игр 

Team Fortress 2 с Source Repair в первый раз был на разных дисках, я подумал что проблема может быть в этом и переустановил игру, но это никак не помогло. После переустановки игру запускал. Всё так же не видит.

**Comment by xvitaly** [comment]
TF2 has been updated to 64-bit version. Already fixed in https://github.com/xvitaly/srcrepair/commit/c77ed94842fd8c29b4329e6662e90b37bf1a5cbc commit.

You need to open the `%LOCALAPPDATA%\SRC Repair\games.xml` file and apply the fix manually or simply download the [latest game database](https://github.com/xvitaly/srcrepair/raw/master/assets/games.xml) and overwrite the existing file.

**Comment by xvitaly** [comment]
TF2 была обновлена до 64-битной версии. Проблема уже исправлена в https://github.com/xvitaly/srcrepair/commit/c77ed94842fd8c29b4329e6662e90b37bf1a5cbc коммите.

Откройте `%LOCALAPPDATA%\SRC Repair\games.xml` файл в текстовом редакторе и вручную примените исправление, либо просто загрузите [самую свежую версию](https://github.com/xvitaly/srcrepair/raw/master/assets/games.xml) базы игр и перезапишите исходный файл.

Следующая версия программы будет содержать данный фикс.

**Comment by s1lentman** [comment]
after redacting the file it worked pretty well, ty very much
